import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(process.argv[2]||path.join(path.dirname(fileURLToPath(import.meta.url)),'../..'));
const read=f=>fs.readFileSync(path.join(root,f),'utf8'),noop=()=>{};
function setup(){
 const events={},els=new Map(),element=id=>{if(!els.has(id))els.set(id,{id,style:{},dataset:{},value:'',textContent:'',innerHTML:'',hidden:false,classList:{toggle(k,v){this[k]=v;},add(k){this[k]=true;},remove(k){delete this[k];},contains(k){return !!this[k];}},addEventListener:noop,focus:noop});return els.get(id);};
 const rows=[{id:'a',datum:'2026-09-04',start:'09:00',eind:'09:01',dossierId:'d',omschrijving:'Werk',soort:'werk'},{id:'b',datum:'2026-09-04',start:'09:01',eind:'09:02',dossierId:'d',omschrijving:'Werk',soort:'werk'}];
 const state={rules:rows,running:null,dossiers:[{id:'d',nummer:'123456789',naam:'Zaak'}],stack:[],dayEnds:{},weekAnchor:'2026-09-04'};let day='2026-09-04';
 const c=vm.createContext({console,Date,Map,Set,Promise,setTimeout,clearTimeout,$:element,document:{activeElement:null,body:{dataset:{}},documentElement:{dataset:{},classList:{toggle:noop}},hasFocus:()=>true,addEventListener:(k,f)=>events[k]=f},window:{addEventListener:noop},ntWizard:null,liveId:null,codeGevraagd:null,NORM:8,VOOR:/^\d{2}\.\d{2}\.\d{4} · [^·]* · /,ac:{},toast:noop,esc:s=>String(s??''),ntRender:noop,checkWake:noop,hideWake:noop,eisCode:noop,dosVeld:d=>d?.naam||'',codeNaam:(d,x)=>x||'',defaultCode:()=>'',ntFocus:noop,ntNieuwState:()=>({id:state.running?.id,step:'search'}),omschrijvingBewaarStatus:()=> 'saved',flushOmschr:async()=>{},ntTerug:noop,HH:{}});
 for(const f of ['js/hh.js','js/domain/time.js','js/domain/booking.js'])vm.runInContext(read(f),c);
 const b=c.HH.domain.booking,t=c.HH.domain.time;
 c.HH.state={read:()=>state};c.HH.ui={modals:{blocksGlobalKeyboard:()=>null}};c.HH.app={render:noop,showTab:noop};c.HH.services={settings:{save:async()=>{}}};c.HH.renderCoordinator={render:noop};
 Object.assign(c,{today:()=>day,werkdag:d=>![0,6].includes(new Date(d+'T12:00:00Z').getDay()),vandaagRegels:()=>state.rules.filter(r=>r.datum===day),dosOf:id=>state.dossiers.find(d=>d.id===id),isIndirect:d=>!!(d?.isI7||d?.voorlopig),isDvn:d=>!!d?.dvn,dvnDefinitiefI7:()=>false,codeFout:()=>false,urenOf:r=>b.hoursOf(r),totaal:rs=>b.totalHours(rs),gapsFor:(rs,d)=>b.gapsFor(rs,{date:d,today:day,nowHM:'09:02'}),gapHours:b.gapHours,hm2m:t.hm2m,eindOf:r=>r.eind||r.start,uu:n=>n.toFixed(1).replace('.',','),parseD:s=>new Date(s+'T12:00:00Z'),addD:(d,n)=>{const v=new Date(d+'T12:00:00Z');v.setUTCDate(v.getUTCDate()+n);return v.toISOString().slice(0,10);},dmy:x=>x,actief:()=>[],takenVandaag:()=>[],favCodes:()=>[]});
 c.sumVan=rs=>b.aggregateIntapp(rs,{getDossier:c.dosOf,getIntappInfo:d=>({nummer:d?.nummer||'',naam:d?.naam||''})});
 vm.runInContext(read('js/core.js').match(/const simIntappTotaal=.*?;/)[0],c);
 const core=read('js/core.js');vm.runInContext(core.slice(core.indexOf('function nuBreakdown('),core.indexOf('function gapsFor(')),c);
 for(const f of ['js/ui/now-recent-view.js','js/ui/week-view.js','js/ui/now-live-view.js'])vm.runInContext(read(f),c);
 return{c,state,el:element,events,setDay:d=>day=d,loadControls(){for(const name of ['terug','vraagHernoemVoorlopig','pauze','eindeWerkdag','hervat','kiesTaak','naStart','renderOpenDagen','sluitWerkdag','undo','markeerVolgt','interrupt','openBoek'])if(!c[name])c[name]=noop;const source=read('js/controls.js');vm.runInContext(source.slice(0,source.indexOf('/* ---------- DVN dossiernummer-sheet')),c);}};
}
const tests=[];const test=(n,f)=>tests.push([n,f]);
test('Nu onderscheidt 0,2 registratie, 0,1 Intapp en 7,9 tekort',()=>{const h=setup();h.c.renderTot();assert.equal(h.el('t-uren').textContent,'0,2');assert.equal(h.el('t-intapp').textContent,'0,1');assert.equal(h.el('t-shortfall').textContent,'7,9');assert.equal(h.el('t-void').textContent,'0,0');assert.match(h.el('t-breakdown').textContent,/Registratie: Declarabel 0,2/);});
test('weekend toont geen tekort of normvoortgang',()=>{const h=setup();h.setDay('2026-09-06');h.c.renderTot();assert.equal(h.el('t-shortfall-wrap').style.display,'none');assert.equal(h.el('t-progress').style.display,'none');assert.match(h.el('t-norm-label').textContent,/weekend/);});
test('Week gebruikt Intapp voor tekort en benoemt registratie apart',()=>{const h=setup();h.c.renderWeek();const html=h.el('w-grid').innerHTML;assert.match(html,/Registratie · per regel afgerond/);assert.match(html,/Intapp-totaal 0,1/);assert.match(html,/7,9 tot 8 uur \(Intapp\)/);assert(!html.includes('7,8 tot 8'));});
test('onvolledige timer blijft zichtbaar herstelbaar na sluiten wizard',()=>{const h=setup();h.state.running={...h.state.rules[0],omschrijving:'',dossierId:null};h.c.renderLive();assert.equal(h.el('l-incomplete').classList.on,true);h.state.running={...h.state.rules[0]};h.c.renderLive();assert.equal(h.el('l-incomplete').classList.on,false);h.state.running.omschrijving='04.09.2026 · Zaak · ';h.c.renderLive();assert.equal(h.el('l-incomplete').classList.on,true);});
test('oude T/O/V toetsen starten geen verborgen timeracties',async()=>{const h=setup();let calls=0;h.c.interrupt=()=>calls++;h.c.markeerVolgt=()=>calls++;h.loadControls();for(const key of ['t','o','v'])await h.events.keydown({key,target:{tagName:'BODY'},preventDefault:noop});assert.equal(calls,0);});
test('gegevens aanvullen houdt dezelfde timer en bewaart eerst de draft',async()=>{const h=setup();h.state.running={...h.state.rules[0],id:'current'};let saves=0,starts=0;h.c.flushOmschr=async()=>saves++;h.c.HH.ui.newTask=()=>starts++;h.loadControls();assert.equal(typeof h.el('b-complete').onclick,'function');await h.el('b-complete').onclick();assert.equal(saves,1);assert.equal(starts,0);assert.equal(h.c.ntWizard.id,'current');assert.equal(h.c.ntWizard.draft,'Werk');});
test('mislukte save blokkeert heropenen van taakinvoer',async()=>{const h=setup();h.state.running=h.state.rules[0];h.c.flushOmschr=async()=>{throw Error('disk');};h.loadControls();assert.equal(typeof h.el('b-complete').onclick,'function');await h.el('b-complete').onclick();assert.equal(h.c.ntWizard,null);});
test('bewaarstatus blijft fout na mislukking en verdwijnt pas na geslaagde retry',async()=>{
 const h=setup(),core=read('js/core.js');let rejectSave=true;
 Object.assign(h.c,{localStorage:{setItem:noop,getItem:()=>null,removeItem:noop},saveRegel:async r=>{if(rejectSave)throw Error('disk');return r;}});
 vm.runInContext(core.slice(core.indexOf('let omsWacht='),core.indexOf('function memRegel(')),h.c);
 h.c.nieuwOmschr('a','Tekst');assert.equal(h.c.omschrijvingBewaarStatus(),'pending');await assert.rejects(h.c.flushOmschr());h.c.renderOpslagStatus();assert.equal(h.c.omschrijvingBewaarStatus(),'error');assert.equal(h.el('b-save-retry').hidden,false);assert.match(h.el('l-save-status').textContent,/niet opgeslagen/);
 rejectSave=false;await h.c.flushOmschr();h.c.renderOpslagStatus();assert.equal(h.c.omschrijvingBewaarStatus(),'saved');assert.equal(h.el('b-save-retry').hidden,true);
});
let fail=0;for(const [n,f]of tests)try{await f();console.log('PASS '+n);}catch(e){fail++;console.error('FAIL '+n+': '+e.message);}console.log(`${tests.length-fail}/${tests.length} Phase Y UI checks passed`);process.exitCode=fail?1:0;
